### ISSUE TITLE
api mode

### ISSUE THREAD

**Issue by vitordino** [asross/settlers#2]
i know this project was probably abandoned, but i would like to know what are the odds and challenge to do a api mode of the backend besides the web and text view

**Comment by vitordino** [comment]
btw, really nice project ✨

**Comment by asross** [comment]
Hey, thanks 😊

Making an API might not be that much work at all, actually! The `Game` object already has an `as_json` method, so based on the request headers, we could probably just send JSON back instead of HTML. Also, are you thinking that someone would use a fully HTTP API (with polling I guess) rather than websockets?

**Comment by vitordino** [comment]
well, i’m open to it.. i personally feels like websocket would probably deliver a better experience, but depending on the json, polling should also be feasible to implement. (i was thinking on creating a decoupled frontend for this, just for fun)

**Comment by asross** [comment]
Oh, I think that might already be possible! The [text client](https://github.com/asross/settlers/blob/master/text/client.rb) essentially does that, using websockets to receive the current game state as JSON and using HTTP to POST back actions! Do you think that will work for you?

**Comment by vitordino** [comment]
yep, i think that works wonderfully 🤘

**Comment by asross** [comment]
Woohoo, awesome :) Let me know how the frontend building goes!
